server:
  port: 8080
#spring:
#  application:
#    name: CI/CD-with-GitHub-Action
#  datasource:
#    url: jdbc:postgresql://localhost:5432/cicd_test
#    username: postgres
#    password: atumar4031


#spring:
#  devtools:
#    add-properties: false
#  datasource:
#    url: jdbc:postgresql://${DB_HOST}/${DB_NAME}?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#  jpa:
#    hibernate.ddl-auto: update
#    generate-ddl: true
#    show-sql: false
